name: Build Book

on:
  push:
    branches: 
      - eco-sailing/preview
      - eco-sailing/highres

jobs:
  build:
    runs-on: ubuntu-latest
    container: jakobkmar/pandoc-all-in-one:latest

    steps:

    - uses: actions/checkout@v4

    - name: Build book
      run: bash pandoc.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: '*.pdf'
